sudo: required

services:
  - docker

before_install:
- echo FROM $(echo $TEST_PLATFORM | tr A-Z a-z):$TEST_RELEASE > Dockerfile
- cat .travis/Dockerfile-$TEST_PLATFORM >> Dockerfile
- docker build -t ansible-clang-$TEST_RELEASE .

script:
- docker run --mount type=bind,source=$PWD,destination=/tmp/ansible-clang -w=/tmp/ansible-clang/.travis ansible-clang-$TEST_RELEASE ansible-playbook playbook.yml

deploy:
  on:
    repo: loderunner/ansible-clang
    branch: master
- ansible-galaxy login --github-token=$GITHUB_TOKEN
- ansible-galaxy import loderunner ansible-clang

env:
  matrix:
    - TEST_PLATFORM=Debian TEST_RELEASE=stretch CLANG_VERSION=5.0
    - TEST_PLATFORM=Debian TEST_RELEASE=stretch CLANG_VERSION=6.0
    - TEST_PLATFORM=Debian TEST_RELEASE=stretch CLANG_VERSION=7
    - TEST_PLATFORM=Debian TEST_RELEASE=sid CLANG_VERSION=5.0
    - TEST_PLATFORM=Debian TEST_RELEASE=sid CLANG_VERSION=6.0
    - TEST_PLATFORM=Debian TEST_RELEASE=sid CLANG_VERSION=7
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=trusty CLANG_VERSION=5.0
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=trusty CLANG_VERSION=6.0
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=trusty CLANG_VERSION=7
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=xenial CLANG_VERSION=5.0
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=xenial CLANG_VERSION=6.0
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=xenial CLANG_VERSION=7
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=artful CLANG_VERSION=5.0
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=artful CLANG_VERSION=6.0
    - TEST_PLATFORM=Ubuntu TEST_RELEASE=artful CLANG_VERSION=7

